    const express=require("express")
    const router=express.Router()
    const cropDetails=require("../controllers/cropDetails")
    const getCropDetails=require("../controllers/getCropDetails")
    const updateCropDetails=require("../controllers/updateCropDetails")
    const deleteCropDetails=require("../controllers/deleteCropDetails")
    const harvestingDetails=require("../controllers/harvestingDetails")
    const getHarvestingDetails=require("../controllers/getHarvestingDetails")
    const updateHarvestingDetails=require("../controllers/updateHarvestingDetails")
    const deleteHarvestingDetails=require("../controllers/deleteHarvestingDetails")
    const storageDetails=require("../controllers/storageDetails")
    const getStorageDetails=require("../controllers/getStorageDetails")
    const updateStorageDetails=require("../controllers/updateStorageDetails")
    const deleteStorageDetails=require("../controllers/deleteStorageDetails")
    const threshingDetails=require("../controllers/threshingDetails")
    const getThreshingDetails=require("../controllers/getThreshingDetails")
    const updateThreshingDetails=require("../controllers/updateThreshingDetails")
    const deleteThreshingDetails=require("../controllers/deleteThreshingDetails")
    const dryingDetails=require("../controllers/dryingDetails")
    const getDryingDetails=require("../controllers/getDryingDetails")
    const updateDryingDetails=require("../controllers/updateDryingDetails")
    const deleteDryingDetails=require("../controllers/deleteDryingDetails")

    router.use("/",cropDetails)
    router.use("/",getCropDetails)
    router.use("/",updateCropDetails)
    router.use("/",deleteCropDetails)
    router.use("/",harvestingDetails)
    router.use("/",getHarvestingDetails)
    router.use("/",updateHarvestingDetails)
    router.use("/",deleteHarvestingDetails)
    router.use("/",storageDetails)
    router.use("/",getStorageDetails)
    router.use("/",updateStorageDetails)
    router.use("/",deleteStorageDetails) 
    router.use("/",threshingDetails)
    router.use("/",getThreshingDetails)
    router.use("/",updateThreshingDetails)
    router.use("/",deleteThreshingDetails)
    router.use("/",dryingDetails)
    router.use("/",getDryingDetails)
   /* router.use("/",updateDryingDetails)
    router.use("/",deleteDryingDetails)*/
    module.exports=router
    